name: Release Circe to GitHub Packages

on:
  push:
    branches:
      - master

jobs:
  build-and-test:
    uses: ./.github/workflows/build.yml

  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          java-version: '8'
          distribution: 'adopt'
      - name: Publish package
        run: mvn --batch-mode deploy
        env:
          GITHUB_TOKEN: ${{ secrets.PUBLISH_TO_ARTIFACTORY }}
